FROM golang:1.25-alpine

RUN apk add --no-cache git ca-certificates \
 && go install github.com/air-verse/air@v1.65.1

WORKDIR /app

COPY go.mod go.sum* ./
RUN go mod download || true

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
